apiVersion: v2
name: website
version: 0.3.0
description: 電算部公式ウェブサイト
type: application
dependencies:
  - name: cloudflare-tunnel
    version: 0.3.0
    repository: https://cloudflare.github.io/helm-charts
appVersion: 2.3.0
