name: Release Charts

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          helm repo add cloudflare https://cloudflare.github.io/helm-charts
      - uses: helm/chart-releaser-action@ed43eb303604cbc0eeec8390544f7748dc6c790d
        with:
          pages_branch: gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
